services:
  # database:
  #   build: ./database
  #   container_name: 'database'

  backend:
    build: ./backend
    restart: always
    container_name: 'backend'
    # depends_on:
    #   - database
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/opt/backend

  frontend:
    build: ./frontend
    restart: always
    container_name: 'frontend'
    # depends_on:
    #   - database
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/opt/frontend
    
  broker:
    build: ./broker
    restart: always
    container_name: 'broker'
    ports:
      - "1883:1883"
    tty: true
    volumes:
      - ./broker/src:/opt/broker

  subscriber:
    build: ./sensor_subscriber
    restart: always
    container_name: 'subscriber'
    depends_on:
      - backend
      - broker
    ports:
      - "1884:1884"
    tty: true
    volumes:
      - ./sensor_subscriber/src:/opt/sensor_subscriber