services:
  # database:
  #   build: ./database
  #   container_name: 'database'

  backend:
    build: ./backend
    restart: always
    container_name: 'backend'
    # depends_on:
    #   - database
    # environment:
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/opt/backend
  
  broker:
    build: ./broker/docker
    restart: always
    container_name: 'broker'
    ports:
      - "1883:1883"
    tty: true
    volumes:
      - ./broker:/opt/broker
    working_dir: /opt/broker
    command: mosquitto -c /opt/broker/mosquitto.conf

  subscriber:
    build: ./sensor_subscriber
    restart: always
    container_name: 'subscriber'
    depends_on:
      - backend
      - broker
    ports:
      - "1884:1884"
    tty: true
    volumes:
      - ./sensor_subscriber/src:/opt/sensor_subscriber