services:
  # database:
  #   build: ./database
  #   container_name: 'database'
  backend:
    build: ./backend/docker
    restart: always
    container_name: 'backend'
    # depends_on:
    #   - database
    # environment:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/backend
    working_dir: /opt/backend
    # command: python3 manage.py runserver 0.0.0.0:8000

  sensor:
    build: ./sensor/docker
    restart: always
    container_name: 'backsensorend'
    # depends_on:
    #   - database
    # environment:
    ports:
      - "8001:8001"
    volumes:
      - ./sensor:/opt/sensor
    working_dir: /opt/sensor