services:
  # database:
  #   build: ./database
  #   container_name: 'database'
  
  backend:
    build: ./backend/docker
    restart: always
    container_name: 'backend'
    # depends_on:
    #   - database
    # environment:
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/opt/backend
    working_dir: /opt/backend
    # command: python3 manage.py runserver 0.0.0.0:8000
  
  broker:
    build: ./broker/docker
    restart: always
    container_name: 'broker'
    ports:
      - "1883:1883"
    tty: true
    volumes:
      - ./broker:/opt/broker
    working_dir: /opt/broker
    command: mosquitto -c /opt/broker/mosquitto.conf

  sensor_subscriber:
    build: ./sensor_subscriber/docker
    restart: always
    container_name: 'sensor_subscriber'
    ports:
      - "1884:1884"
    tty: true
    volumes:
      - ./sensor_subscriber:/opt/brsensor_subscriberoker
    working_dir: /opt/sensor_subscriber
    command: mosquitto_sub -d -h 192.168.1.18 -p 1883 -t kame/temp
