# Generated by Django 5.1 on 2024-08-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_mail_address_user_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='mail_address',
        ),
    ]
