# Generated by Django 5.1 on 2024-08-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_individual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tank_id', models.IntegerField()),
                ('turbidity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tank_id', models.IntegerField()),
                ('water_temperature', models.FloatField()),
            ],
        ),
    ]
